In [1]:
%load_ext autoreload

In [2]:
import os, sys
import numpy as np
import pandas as pd

import tensorflow as tf
import tensorflow.keras as keras

In [3]:
BASE_PATH = os.path.join(os.getcwd(), "..", "..")

MODULES_PATH = os.path.join(BASE_PATH, "modules")
DATASETS_PATH = os.path.join(BASE_PATH, "datasets")
os.listdir(DATASETS_PATH)

['fashion_mnist',
 'caltech_ucsd_birds200',
 'baffin_bay',
 'mnist',
 'reg_data_wilson_izmailov']

In [4]:
sys.path.append(MODULES_PATH)

In [5]:
from data import BenchmarkData
from models import setup_growth

In [6]:
(x_train, y_train), (x_test, y_test) = keras.datasets.cifar10.load_data()

In [7]:
x_train.shape

(50000, 32, 32, 3)

In [8]:
y_train.shape

(50000, 1)

In [9]:
num_classes = len(np.unique(y_train))
print("Number of classes {}".format(num_classes))

Number of classes 10


In [10]:
setup_growth()

1 Physical GPU's,  1 Logical GPU's


In [21]:
mobile_net = keras.applications.MobileNetV2(
    weights=None,
    classes=num_classes,
    classifier_activation="softmax"
)

In [18]:
x_train[:2].shape

(2, 32, 32, 3)

In [24]:
output = mobile_net(x_train[:2])
output

<tf.Tensor: shape=(2, 10), dtype=float32, numpy=
array([[0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]], dtype=float32)>

In [27]:
mobile_net.compile(
    loss="sparse_categorical_crossentropy", 
    optimizer="adam", 
    metrics=[keras.metrics.SparseCategoricalAccuracy()]
)

In [28]:
mobile_net.fit(x_train, y_train, epochs=100, batch_size=100)

Epoch 1/100
500/500 [==============================] - 13s 25ms/step - loss: 1.0749 - sparse_categorical_accuracy: 0.6265
Epoch 2/100
500/500 [==============================] - 12s 25ms/step - loss: 0.9823 - sparse_categorical_accuracy: 0.6562
Epoch 3/100
500/500 [==============================] - 13s 25ms/step - loss: 0.9152 - sparse_categorical_accuracy: 0.6802
Epoch 4/100
500/500 [==============================] - 13s 26ms/step - loss: 0.7948 - sparse_categorical_accuracy: 0.7222
Epoch 5/100
500/500 [==============================] - 13s 26ms/step - loss: 0.7433 - sparse_categorical_accuracy: 0.7398
Epoch 6/100
500/500 [==============================] - 13s 26ms/step - loss: 0.7060 - sparse_categorical_accuracy: 0.7545
Epoch 7/100
500/500 [==============================] - 13s 26ms/step - loss: 0.6426 - sparse_categorical_accuracy: 0.7753
Epoch 8/100
500/500 [==============================] - 13s 26ms/step - loss: 0.8387 - sparse_categorical_accuracy: 0.7175
Epoch 9/100
500/500 [===

500/500 [==============================] - 13s 27ms/step - loss: 0.1154 - sparse_categorical_accuracy: 0.9588
Epoch 65/100
500/500 [==============================] - 11s 23ms/step - loss: 0.1146 - sparse_categorical_accuracy: 0.9592
Epoch 66/100
500/500 [==============================] - 12s 25ms/step - loss: 0.1104 - sparse_categorical_accuracy: 0.9605
Epoch 67/100
500/500 [==============================] - 14s 27ms/step - loss: 0.1184 - sparse_categorical_accuracy: 0.9579
Epoch 68/100
500/500 [==============================] - 13s 26ms/step - loss: 0.0985 - sparse_categorical_accuracy: 0.9651
Epoch 69/100
500/500 [==============================] - 13s 27ms/step - loss: 0.1020 - sparse_categorical_accuracy: 0.9639
Epoch 70/100
500/500 [==============================] - 13s 26ms/step - loss: 0.0988 - sparse_categorical_accuracy: 0.9655
Epoch 71/100
500/500 [==============================] - 13s 27ms/step - loss: 0.1012 - sparse_categorical_accuracy: 0.9655
Epoch 72/100
500/500 [=======

In [36]:
new_output = mobile_net(x_test[:2])
new_output

<tf.Tensor: shape=(2, 10), dtype=float32, numpy=
array([[2.4119317e-05, 1.6046250e-04, 9.2549426e-06, 6.3442996e-05,
        9.7207794e-07, 9.9591357e-01, 1.1461984e-06, 9.1412693e-04,
        2.9104636e-03, 2.4777989e-06],
       [1.1590678e-10, 4.8099764e-11, 1.5533098e-22, 1.3188160e-28,
        3.3233719e-25, 1.0059743e-19, 1.1733457e-14, 2.3989667e-30,
        1.0000000e+00, 1.1549327e-13]], dtype=float32)>

In [38]:
y_test[:2]

array([[3],
       [8]], dtype=uint8)

In [39]:
tf.math.argmax(new_output, axis=1)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([5, 8])>